sed -i 's/Icons.Default.ColorLens/Icons.Default.Brush/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.InvertColors/Icons.Default.Edit/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.AutoAwesome/Icons.Default.Star/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.VerticalSplit/Icons.Default.CallSplit/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.Speed/Icons.Default.PlayArrow/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.Animation/Icons.Default.Build/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.ViewInAr/Icons.Default.Layers/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.MergeType/Icons.Default.ViewHeadline/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.CropRotate/Icons.Default.Refresh/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.StarOutline/Icons.Default.Star/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.GraphicEq/Icons.Default.Share/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
sed -i 's/Icons.Default.Tune/Icons.Default.Settings/g' feature/editor/src/main/java/com/example/feature/editor/EditorScreen.kt
