sed -i 's/Icons.Default.Cut/Icons.Default.ContentCut/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.AutoAwesome/Icons.Default.Star/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.PhotoFilter/Icons.Default.Build/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.WandStyle/Icons.Default.AutoFixHigh/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.Subtitles/Icons.Default.ClosedCaption/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.ArtTrack/Icons.Default.Image/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.Store/Icons.Default.ShoppingCart/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.GraphicEq/Icons.Default.Headphones/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.ChevronRight/Icons.Default.KeyboardArrowRight/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
sed -i 's/Icons.Default.AddBox/Icons.Default.AddCircle/g' feature/home/src/main/java/com/example/feature/home/HomeScreen.kt
